platform :ios, '15.0'

target 'PhoneCam' do
  use_frameworks!
  pod 'WebRTC-SDK', '~> 114.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # 手动签名时，Pods framework 不需要 provisioning profile
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGN_STYLE'] = ''
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end
end
