platform :ios, '15.0'

target 'PhoneCam' do
  use_frameworks!
  pod 'WebRTC-SDK', '~> 114.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Pods framework 手动签名，使用证书但不需要 provisioning profile
      config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
      config.build_settings['CODE_SIGN_IDENTITY'] = 'Apple Development'
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'YES'
      config.build_settings['DEVELOPMENT_TEAM'] = '7KQ4Z998AK'
    end
  end
end
