name: PhoneCam
options:
  xcodeVersion: "15.0"
  createIntermediateGroups: true
packages:
  SRTKit:
    path: SRTKit
targets:
  PhoneCam:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - PhoneCam
    resources:
      - PhoneCam/Assets.car
    dependencies:
      - package: SRTKit
        product: libsrt
    settings:
      base:
        INFOPLIST_FILE: PhoneCam/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yzg.phonecam
        DEVELOPMENT_TEAM: "7KQ4Z998AK"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "iPhone Developer"
        PROVISIONING_PROFILE_SPECIFIER: phonecam
        CODE_SIGNING_REQUIRED: YES
        CODE_SIGNING_ALLOWED: YES
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        CLANG_ENABLE_MODULES: YES
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
schemes:
  PhoneCam:
    build:
      targets:
        PhoneCam: all
