name: PhoneCam
options:
  xcodeVersion: "15.0"
  createIntermediateGroups: true
targets:
  PhoneCam:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - PhoneCam
    settings:
      base:
        INFOPLIST_FILE: PhoneCam/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yzg.phonecam
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        CLANG_ENABLE_MODULES: YES
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: ""
        Release:
          CODE_SIGN_IDENTITY: ""
    dependencies:
      - framework: Pods_PhoneCam.framework
        implicit: true
schemes:
  PhoneCam:
    build:
      targets:
        PhoneCam: all
